apiVersion: v2
name: s3proxy
description: A Helm chart for use s3proxy in K8s
annotations:
  org.opencontainers.image.source: "https://github.com/intrinsec/s3proxy/"
type: application
version: 1.7.0
appVersion: "1.7.0"
