replicaCount: 1

image:
  repository: ghcr.io/k3s-argocd-cluster/s3proxy
  pullPolicy: IfNotPresent
  # tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Can add "--no-tagging" if you don't want to use x-amz-tagging header
#  This enables the s3proxy to also be used with i.e. BackBlaze S3 bucket store
#  Please note this should not break any functionality. Although there is an DekTag attribute, its value
#  actually is written into the metadata to that object, not an explicit tag.
# Can add "--no-tls" if you don't want TLS
#  By default, listenning TLS with files /etc/s3proxy/certs/s3proxy.crt & /etc/s3proxy/certs/s3proxy.key
#  When disabling TLS, make sure to revisit liveness and readiness probes (and change from HTTPS to HTTP)
# Can add "--cache=memory" if you want to cache some of the GET and HEAD requests locally
#  In theory, this will reduce the amount of premium calls into backends such as BackBlaze
# Must add "--level=?" to specify logging level. Available values are
#  -2 = Tracing
#  -1 = Debug
#   0 = Info
#   1 = Warning
#   2 = Error
args: ["--level=0"]

cert: # From CertManager CRD
  enable: false
  issuerRefKind: ClusterIssuer
  # issuerRefName: internal-company-com
  # commonName: "*.s3proxy.internal.company.com"

config:
  host: s3.us-east-1.amazonaws.com
  # throttling: 5
  # accessKey: CHANGEME
  # secretKey: CHANGEME
  # encryptKey: CHANGEME
  # existentSecret: s3proxy-secret
valsSecret: {}
#   accessKey: ref+vault://s3proxy/secrets/access-key
#   secretKey: ref+vault://s3proxy/secrets/secret-key
#   encryptKey: ref+vault://s3proxy/secrets/encrypt-key

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 4433

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /healthz  # Liveness endpoint
    port: 4433
    scheme: HTTPS
readinessProbe:
  httpGet:
    path: /readyz  # Readiness endpoint
    port: 4433
    scheme: HTTPS

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

# Additional volumes on the output Deployment definition.
extraVolumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
extraVolumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
